sql:
  host:
  port:
  database:
  username:
  password:

settings:
  limits:
    cityname: 16
    citygoname: 20
    citygodisplayname: 30
    motd: 250
    entermessage: 225
    exitmessage: 225

  maxbantime: 10y
  cooldownTime:
    invite: 180
    namechange: 43200
  city:
    creationcost: 500000
    startingbalance: 200000
    gocost: 5000
    startingtax: 2
    claimcost: 500
    bonuscost: 800
    citygocost: 10000
    outpostcost: 15000