sql:
  host:
  port:
  database:
  username:
  password:

settings:
  locale: sv_se
  limits:
    cityname: 16
    citygoname: 42
    citygodisplayname: 42
    motd: 250
    entermessage: 225
    exitmessage: 225
    plotname: 16
    districtname: 26
    maxbantime: 10y
    citymaxtax: 10.00

    maxamountofplots: 500

    minchunkdistance: 400
    minspawndistance: 2000

  renttime:
    day: 1
    hour: 23
    minute: 59
    second: 0

  taxtime:
    hour: 0
    minute: 0
    second: 0

  cooldownTime:
    invite: 180
    namechange: 2592000
  city:
    statetax: 4
    creationcost: 500000
    startingbalance: 200000
    gocost: 5000
    startingtax: 2
    claimcost: 500
    bonuscost: 800
    citygocost: 10000
    outpostcost: 15000
    districtcost: 10000
    startingtaxlevel: "mayor"
    default:
      plotFlags: ""
      cityFlags: "am"
      memberPerms: "gt"
      outsiderPerms: "gt"
  jail:
    dailypayback: 100
    prisonerpayback: 100

  teleportcooldown: 3

  leaderboard:
    blockfilter:
    mobfilter:
