name: Metropolis
version: '${project.version}'
main: live.supeer.metropolis.Metropolis
api-version: '1.21'
authors: [ Supeeer ]
description: A kinda cool plugin
website: supeer.live
depend:
  - Apied
  - CoreProtect
